development:
  adapter: postgresql
  encoding: unicode
  database: famlink_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: famlink_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: famlink
  host: localhost
  pool: 5
